# Generated by Django 2.1 on 2018-10-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('word', models.CharField(max_length=50, unique=True)),
                ('part_of_speech', models.CharField(max_length=50)),
                ('definition', models.TextField()),
                ('example', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
