# Generated by Django 2.1 on 2018-10-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('-added',)},
        ),
    ]
