# Generated by Django 2.1 on 2018-10-13 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_auto_20181013_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing_question',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
