# Generated by Django 2.1.2 on 2018-10-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_writing_question_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='question',
            field=models.CharField(max_length=10),
        ),
    ]
